### ISSUE TITLE
[Mock observations] Generates odd timestamp

### ISSUE THREAD

**Issue by MariamKhalatova** [Green-Software-Foundation/if-plugins#52]
Run the following manifest. 
 **Actual result:** In the output the last timestamp should not be generated. As it exceeds the time window.
(see the screenshot attached)

```
name: My Manifest File
description: My First Manifest File 💚
# aggregation:
#   metrics:
#     - 'carbon'
#   type: 'both'
initialize:
  outputs: [log]
  plugins: 
    group-by: 
      path: 'builtin'
      method: GroupBy   
    operational-carbon:
      path: '@grnsft/if-plugins'
      method: Multiply
      global-config:
        input-parameters: ['cpu/energy', 'grid/carbon-intensity']
        output-parameter: 'carbon'       
    watttime:
      path: '@grnsft/if-unofficial-plugins'           
      method: WattTimeGridEmissions    
    teads-curve:
      path: '@grnsft/if-unofficial-plugins'
      method: TeadsCurve
      global-config:
        interpolation: spline  
    cloud-metadata:
      method: CloudMetadata
      path: "@grnsft/if-plugins"   
    mock-observations:
      path: '@grnsft/if-plugins'
      method: MockObservations
      global-config:
        timestamp-from: '2024-03-05T00:00:00.000Z'
        timestamp-to: '2024-03-05T00:01:00.000Z'
        duration: 10
        components:
          - name: server-1
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3
          - name: server-2
            cloud/instance-type: Standard_E64_v3
            cloud/region: westus3          
        generators:
          common:
            cloud/vendor: azure
          randint:
            cpu/utilization:
              min: 1
              max: 99           
    'time-sync':
      method: TimeSync
      path: "builtin"
      global-config: 
        start-time: '2024-03-05T00:00:00.000Z'
        end-time: '2024-03-05T00:01:00.000Z'
        interval: 5
        allow-padding: true
tree: 
  pipeline:
    - mock-observations
    - group-by
    # - time-sync
    # - cloud-metadata
    # - watttime
    # - teads-curve
    # - operational-carbon
  defaults:
  config:
    group-by:
      group:
        - cloud/region
        - name
  inputs: null
```

![Image](https://github.com/Green-Software-Foundation/if-plugins/assets/109615222/b69fc6aa-d93c-4d9b-a42f-34c0cb6ba058)
