### ISSUE TITLE
Queries regarding `shell` plug-in

### ISSUE THREAD

**Issue by pangteckchun** [Green-Software-Foundation/if-plugins#87]
Hi, I have the following questions regarding the `shell` plug-in.

## Question 1 - how to run the example given (can't seemed to achieve the output per illustrated ##
Attempted to run the `shell.yml` provided and also downloaded `sampler.py` from the repo.. I can't seemed to get the sample output per illustrated and these are the observations:

1. Using **yaml** as output - no error but the output[] section is empty (it should produce the following outputs):
```
  outputs:
        - timestamp: 2023-07-06T00:00
          duration: 1 # Secs
          cpu/energy: 0.002
          memory/energy: 0.000005
          energy: 0.02 # added by plugin
```
2. Not using **yaml** output and with `--verbose` flag the following error was observed:
```
D:\code\green.software\impact-framework>ie --verbose --manifest ./shell-try.yml
[2024-05-01 05:34:10.004 PM] info:
[!important] Incubation Project

This project is an incubation project being run inside the Green Software Foundation; as such, we DON’T recommend using it in any critical use case.
Incubation projects are experimental, offer no support guarantee, have minimal governance and process, and may be retired at any moment. This project may one day graduate, in which case this disclaimer will be removed.

[2024-05-01 05:34:10.078 PM] error:     "initialize.outputs" parameter is expected array, received null. Error code: invalid_type.
ManifestValidationError:        "initialize.outputs" parameter is expected array, received null. Error code: invalid_type.
    at validate (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\util\validations.js:61:15)
    at validateManifest (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\util\validations.js:53:61)
    at load (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\load.js:14:69)
    at async impactEngine (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\index.js:23:47)
```

This is my env:
`manifest file`:
```
name: shell-demo
description:
tags:
initialize:
  outputs:
    # - yaml
  plugins:
    sampler:
      method: Shell
      path: "@grnsft/if-plugins"
      global-config:
        command: python ./samples.manifest/sampler.py
tree:
  children:
    child:
      pipeline:
        - sampler
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1 # Secs
          cpu/energy: 0.002
          memory/energy: 0.000005
```  
sampler.py @ this file path: ./samples.manifest/sampler.py (no change to contents).
What could I have done wrongly here?

---

## Question 2 - how does IF support the yaml processing if I use my own shell program? ##
I will be writing a custom go program for my needs to call from `shell` plug-in.
Can I know:
1. Does the `shell` plug-in expect my custom program to process the entire manifest file (i.e. each line) or otherwise, which means we would just need to handle `inputs` section?
2.  Same question applies to `outputs` section - do we write the entire yaml manifest out line by line or just need to handle writing for `outputs` ?

Thank you for your attention!
