### ISSUE TITLE
`grafana-exporter` sample did not work

### ISSUE THREAD

**Issue by pangteckchun** [Green-Software-Foundation/if-plugins#89]
Hi, I noticed the `csv-exporter` was renamed to `grafana-exporter` 3 days ago.
I tried to run the sample but am getting the following error:
```
[2024-05-03 03:58:35.774 PM] error:     plugin is not a function
TypeError:      plugin is not a function
    at initPlugin (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\initialize.js:88:12)
    at async initalize (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\lib\initialize.js:96:24)
    at async impactEngine (C:\Users\p1337447\AppData\Roaming\npm\node_modules\@grnsft\if\build\index.js:25:31)
```

The manifest file is this (same sample but only output file path is changed):
```
name: grafana-export-demo
description: example exporting output to a csv file
tags:
initialize:
  outputs:
    - yaml
  plugins:
    grafana-exporter:
      method: GrafanaExport
      path: "@grnsft/if-plugins"
tree:
  children:
    child:
      pipeline:
        - grafana-exporter
      config:
        grafana-exporter:
          output-path: D:\code\green.software\impact-framework\grafana-export.csv
          headers:
            - timestamp
            - duration
            - carbon
            - energy
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 1
          carbon-operational: 0.02
          carbon-embodied: 5
          energy: 3.5
          carbon: 5.02
        - timestamp: 2023-07-06T00:10
          duration: 1
          operational-carbon: 0.03
          carbon-embodied: 4
          energy: 2.9
          carbon: 4.03
```
Version / env:
D:\code\green.software\impact-framework>npm -g list
C:\Users\p1337447\AppData\Roaming\npm
+-- @grnsft/if-plugins@v0.3.2
+-- @grnsft/if-unofficial-plugins@v0.3.1
+-- @grnsft/if@v0.3.2

Thank you for your attention!

TC
